### ISSUE TITLE
[DOC] Add Screenshots in README.md

### ISSUE THREAD

**Issue by Akshu-on-github** [Akshu-on-github/Make-your-own-README.md#7]
## Description
Add screenshots of commit c974979 from my [profile page](https://github.com/Akshu-on-github/Akshu-on-github) at the top of the README.md of this repo:
- In Light Mode
- In Dark Mode

### Additional Context
Adding a screenshot of the realized version can:
- Help visualize the composition
- Identify customizable components

- [x] This issue has been assigned
- [x] The assignee has read the [Code of Conduct](CODE_OF_CONDUCT.md) and the [Contributing Guidelines](CONTRIBUTING.md)

**Comment by saksham-s1ngh** [comment]
I didn't quite understand the issue, should I take a screenshot of the commit (i.e. the lines of code added/deleted) or the result of the commit?

**Comment by Akshu-on-github** [comment]
> should I take a screenshot of the commit (i.e. the lines of code added/deleted) or the result of the commit?

The result/output of the code as of the mentioned commit @saksham-s1ngh

**Comment by saksham-s1ngh** [comment]
Could I be assigned this issue? I was looking for beginner issues, and I probably feel like I could try this one.

**Comment by Akshu-on-github** [comment]
Sure thing - let me know if you need any help 😁

**Comment by Akshu-on-github** [comment]
May I confirm if you've read the coc and guidelines?

**Comment by saksham-s1ngh** [comment]
> May I confirm if you've read the coc and guidelines?

Yes I've read and checked them out. Will go through them once again for good measure.😁

**Comment by saksham-s1ngh** [comment]
How do I attach the screenshots to the readme? Do I upload to a cloud storage and use a link? 😅

**Comment by Akshu-on-github** [comment]
Ah, this is one of GitHub's cool features - just copy paste it to the `.md` (markdown) file
You can also `ctrl+v` the photo(s) onto an issue comment too
